version: '2'
services:
  gitlab-ce:
    name: gitlab-runner-container
    restart: always
    build: .
    networks:
      setting-network:
        ipv4_address: 172.13.1.11
    volumes:
     - /srv/gitlab-runner/data:/home/gitlab-runner/:rw
     - /var/run/docker.sock:/var/run/docker.sock



# --add-host gitlab.ejemplo.dev:172.13.1.10
